### ISSUE TITLE
Can't restore selectively pinned 📌 tabs position

### ISSUE THREAD

**Issue by rediffusion** [danericweiner/pin-unpin-all#2]
If I've selectively (with chrome's implemented option) pinned tabs

![pin](https://user-images.githubusercontent.com/30071027/170780837-9172e91b-5cfe-4b6d-982c-4c8de746f13c.png)

for example, 3 when I click on "Pin Unpin All" it can't restore the positions of 3 tabs. They will be opened from left to right.
Let’s say I've 20 opened tabs, I've pinned the 17th in the browser, how can I restore the position?
[screencast](https://www.screencast.com/t/FyS1CS52ZM)

Go get ’em, tiger 🐯

**Comment by danericweiner** [comment]
Closing as pinning and unpinning a tab (without this extension) updates the tab position.
